### ISSUE TITLE
wrong answer

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#10]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-20/code_cpp/check_prime_num_solution2.cpp](url)

25 is not prime number

also while is conditianal loop, for is iterator loop

**Comment by Altantur** [comment]
Fixed with [THIS](https://github.com/Altantur/algorithms/commit/0c980f0ea03e97c688d7e9f89e04e2963df5653f) commit.
