### ISSUE TITLE
big number 

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#12]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-27/code_cpp/solution_1.cpp](url)

sometimes max int is 3200064
but reverse number might be overflow 4600023, it is higher than maximum value

**Comment by Altantur** [comment]
Should've resolved with [THIS](https://github.com/Altantur/algorithms/commit/7c4694c87758aa702aa5a530bea7e9bb84d69691) commit.
