### ISSUE TITLE
did u check array which contains only 1 element

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#13]
[subarray_solution1.cpp](https://github.com/Altantur/algorithms/blob/master/basics/problem-30/code_cpp/subarray_solution1.cpp)

answer will be 1, but yours 0, am i right?

**Comment by Altantur** [comment]
You are damn right! Fixed with [THIS](https://github.com/Altantur/algorithms/commit/bcd07d2e689d67597eadb8fb447243f1433a0ff4) commit.
