### ISSUE TITLE
array limits

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#14]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-32/code_cpp/linear_search_solution1.cpp](url)

we have a[n] array, last element is a[n-1],

after for loop i will be n , so??

**Comment by Altantur** [comment]
So it will not fail. Because it is ``break`` command that prevents increment after value found.

**Comment by Altantur** [comment]
Fixed with [THIS](https://github.com/Altantur/algorithms/commit/f37f0ebd976e2bc073680e6ad4df3d877f16bbca) commit.
