### ISSUE TITLE
sometimes while is better

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#15]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-33/code_cpp/is_sorted_array_solution1.cpp](url)

int a[n + 1], i =1;

a[n] = a[n - 1] - 1;
while(a[i-1] <= a[i]) 
   i++;
if (i < n)
  false
else
  true

**Comment by Altantur** [comment]
Enhanced with [THIS](https://github.com/Altantur/algorithms/commit/39bb62aeee3e6b24e730aaa3f5fb353eccb1f097) commit. I will see if while is better for this case. Until then it is better to close.
