### ISSUE TITLE
keep it simple stupid

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#16]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-34/code_cpp/change_sorted_array_solution1.cpp](url)

we can count > chars ,. also we need some readable variable name

**Comment by Altantur** [comment]
``i`` is iterator
``n`` is number of elements
``changes``  is how many changes should be made
isn't it KISS ?
If you find some complex or misunderstood part, please reopen and let me know.
