### ISSUE TITLE
it is correct, let me show my solution

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#17]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-39/code_cpp/duplicate_entry_solution1.cpp](url)

cin >> last;
count = 1;
do{
   prev = last;
   cin >> last;
   count++;
}while(last!=prev);

**Comment by Altantur** [comment]
Yes, you are right! I just cleaned code as you suggested with [THIS](https://github.com/Altantur/algorithms/commit/494b12fd66e3a52578155b3252686b6dbd3b46d7) commit. Thanks.
