### ISSUE TITLE
how is that?

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#18]
[https://github.com/Altantur/algorithms/blob/master/basics/problem-41/code_cpp/uniq_digits_solution1.cpp](url)

int digit[3];

for (digit[0] = 1; digit[0] < 10; digit[0]++)
   for (digit[1] = 0; digit[1] < 10; digit[1]++)
       for (digit[2] = 0; digit[2] < 10; digit[2]++)
           if (digit[1] != digit[2] && digit[10 != digit[1] && digit[0] != digit[2])
                cout << digit[0] << digit[1] << digit[2] << " ";

**Comment by Altantur** [comment]
Fixed and cleaned in [THIS](https://github.com/Altantur/algorithms/commit/35945d18e2e6712aa208df8a06d773c353c36554) commit, thanks!
