### ISSUE TITLE
problem_3

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#3]
[triangle_area_solution1.cpp](https://github.com/altantur/algorithms/blob/master/basics/problem-3/code_cpp/triangle_area_solution1.cpp)

if sum of a , b and c is odd, then answer will be wrong.

So u should better fix this

P = a + b + c
S= sqrt((p - 2 * a) * (p - 2 * b) * (p - 2 * c) / 8)

and also u can use double or float numbers

**Comment by Altantur** [comment]
It is float numbers from the beginning! Will be in separated file as you suggested.  
Therefore it is no bug, I think I should close this issue
