### ISSUE TITLE
abs fabs

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#4]
[max_of_2_solution2.cpp](https://github.com/Altantur/algorithms/blob/master/basics/problem-9/code_cpp/max_of_2_solution2.cpp)

include <math> or cmath

and we can use abs() function or fabs function

**Comment by Altantur** [comment]
I thought it is better to understand behind the logic. I am not aware of how abs() works in back but it can replaced by such actions. However, I just added comment to clarify abs() function.

Therefore there is no error I will close this issue. 
Please reopen this issue if you have a problem.
