### ISSUE TITLE
not solved

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#5]
[median_of_3_solution1.cpp](https://github.com/Altantur/algorithms/blob/master/basics/problem-10/code_cpp/median_of_3_solution1.cpp)

all answer is 0

**Comment by Altantur** [comment]
Should be resolved with [THIS](https://github.com/Altantur/algorithms/commit/998dda7d8d344860300235281d59457b4320ea34) commit. 
Please reopen if there is a problem.
