### ISSUE TITLE
must be write simple code

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#6]
[second_max_of_4_solution1.cpp](https://github.com/Altantur/algorithms/blob/master/basics/problem-11/code_cpp/second_max_of_4_solution1.cpp)

would you prefer sorting as asc than desc,
so u dont need to sort all element .
a b c d
step 1 : a<>b, b<>c, c<>d        most maximum element is d
step 2 : a<>b
step 3:  second element is max(b,c)

**Comment by Altantur** [comment]
Fixed [THIS](https://github.com/Altantur/algorithms/commit/80f7cbeb62a5fd92275e0d69426b0963a2cad78a) commit. 
Please reopen this issue if you have a problem.
