### ISSUE TITLE
too many if

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#7]
[4_integers_solution1.cpp](https://github.com/Altantur/algorithms/blob/master/basics/problem-13/code_cpp/4_integers_solution1.cpp)

p = 1;
negatives = 0;
if (a < 0) {
   p *=a;
  negatives++;
}
.......

**Comment by Altantur** [comment]
Find with [THIS](https://github.com/Altantur/algorithms/commit/06b8c346a2f62f142e69fcba8b56cdbf4585f159) commit. 
Please reopen this issue if you have a problem.

**Comment by Altantur** [comment]
Fixed and complete in [THIS](https://github.com/Altantur/algorithms/commit/c1e2c9c57dc40b07d6632b669e3c801c4b00d6e8)commit. Thanks!
