### ISSUE TITLE
sometimes we need little math skills

### ISSUE THREAD

**Issue by Amartaivan** [Altantur/algorithms#8]
arithmetic sequence
[problem-15/code_cpp](https://github.com/Altantur/algorithms/tree/master/basics/problem-15/code_cpp)

**Comment by Altantur** [comment]
Fixed with [THIS](https://github.com/Altantur/algorithms/commit/db91a656af46c465a19b1e7d4d82594527d0cabe) commit.
Please reopen this issue if you have a problem.
